Repository carbon-design-system/gatsby-theme-carbon, pull requests merged in 2019-07, with the labels that each got.

#215 chore: add IDL video design to video component
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/AlertBanner.js
  packages/gatsby-theme-carbon/src/components/ArticleCard/ArticleCard.js
  packages/gatsby-theme-carbon/src/components/AutolinkHeader/AutolinkHeader.js
  packages/gatsby-theme-carbon/src/components/DoDontExample/DoDontExample.js
  packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js
  packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearchInput.js
  packages/gatsby-theme-carbon/src/components/Header/Header.js
  packages/gatsby-theme-carbon/src/components/ImageCard/ImageCard.js
  packages/gatsby-theme-carbon/src/components/ImageComponent/ImageComponent.js
  packages/gatsby-theme-carbon/src/components/LeftNav/ResourceLinks.js
  packages/gatsby-theme-carbon/src/components/ResourceCard/ResourceCard.js
  packages/gatsby-theme-carbon/src/components/Video/Video.js
  packages/gatsby-theme-carbon/src/components/Video/Video.module.scss
  yarn.lock
Labels: status: ready to merge :tada:

#218 fix: allow favicon override
  README.md
  packages/gatsby-theme-carbon/gatsby-config.js
  packages/gatsby-theme-carbon/src/images/favicon.png
Labels: status: ready to merge :tada:

#216 Themes
  packages/gatsby-theme-carbon/gatsby-config.js
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/Accordion/Accordion.module.scss
  packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLinks.module.scss
  packages/gatsby-theme-carbon/src/components/Aside/Aside.module.scss
  packages/gatsby-theme-carbon/src/components/AutolinkHeader/AutolinkHeader.module.scss
  packages/gatsby-theme-carbon/src/components/Code/Code.js
  packages/gatsby-theme-carbon/src/components/Code/index.js
  packages/gatsby-theme-carbon/src/components/Container/Container.js
  packages/gatsby-theme-carbon/src/components/Container/Container.module.scss
  packages/gatsby-theme-carbon/src/components/Container/index.js
  packages/gatsby-theme-carbon/src/components/EditLink/EditLink.js
  packages/gatsby-theme-carbon/src/components/EditLink/EditLink.module.scss
  packages/gatsby-theme-carbon/src/components/EditLink/index.js
  packages/gatsby-theme-carbon/src/components/FeatureCard/FeatureCard.js
  packages/gatsby-theme-carbon/src/components/FourOhFour/FourOhFour.module.scss
  packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
  packages/gatsby-theme-carbon/src/components/Homepage/Banner.js
  packages/gatsby-theme-carbon/src/components/Homepage/Banner.module.scss
  packages/gatsby-theme-carbon/src/components/Homepage/Callout.js
  packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss
  packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.js
  packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.module.scss
  packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavWrapper.js
  packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavWrapper.module.scss
  packages/gatsby-theme-carbon/src/components/Main/Main.module.scss
  packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.module.scss
  packages/gatsby-theme-carbon/src/components/PageDescription/PageDescription.module.scss
  packages/gatsby-theme-carbon/src/components/PageHeader/PageHeader.module.scss
  packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.module.scss
  packages/gatsby-theme-carbon/src/components/Switcher/Switcher.module.scss
  packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss
  packages/gatsby-theme-carbon/src/components/Video/Video.js
  packages/gatsby-theme-carbon/src/components/Video/Video.module.scss
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
  packages/gatsby-theme-carbon/src/styles/index.scss
  packages/gatsby-theme-carbon/src/styles/internal/_global.scss
  packages/gatsby-theme-carbon/src/styles/internal/_page.scss
  packages/gatsby-theme-carbon/src/styles/internal/g10.scss
  packages/gatsby-theme-carbon/src/styles/internal/resources.scss
  yarn.lock
Labels: status: merge conflict :no_entry_sign:

#230 docs(getting-started): Punchier intro paragraph
  packages/example/src/pages/getting-started/index.mdx
Labels: status: ready for review :eyes:, type: docs :book:

#243 Homepage callout alignment
  .gitignore
  package.json
  packages/example/src/gatsby-theme-carbon/templates/Homepage.module.scss
  packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss
  packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss
  packages/gatsby-theme-carbon/src/components/ImageComponent/image-component.scss
  packages/gatsby-theme-carbon/src/components/PageTable/page-table.scss
Labels: status: ready for review :eyes:

#246 chore: update anchor link spacing
  packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLinks.module.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#244 chore: update video spacing to match IDL site
  packages/gatsby-theme-carbon/src/components/Video/Video.module.scss
Labels: status: one more review :eyes:, status: visual review :eyes:

#242 Code snippet
  packages/example/src/data/nav-items.yaml
  packages/example/src/pages/components/Accordion.mdx
  packages/example/src/pages/components/AnchorLinks.mdx
  packages/example/src/pages/components/ArticleCard.mdx
  packages/example/src/pages/components/Aside.mdx
  packages/example/src/pages/components/Caption.mdx
  packages/example/src/pages/components/DoDontExample.mdx
  packages/example/src/pages/components/FeatureCard.mdx
  packages/example/src/pages/components/Grid.mdx
  packages/example/src/pages/components/ImageCard.mdx
  packages/example/src/pages/components/PageDescription.mdx
  packages/example/src/pages/components/ResourceCard.mdx
  packages/example/src/pages/components/Tabs.mdx
  packages/example/src/pages/components/Video.mdx
  packages/example/src/pages/components/code-blocks.mdx
  packages/example/src/pages/components/markdown.mdx
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/Code/Code.js
  packages/gatsby-theme-carbon/src/components/Code/Code.module.scss
  packages/gatsby-theme-carbon/src/components/Code/PathRow.js
  packages/gatsby-theme-carbon/src/components/Code/Sidebar.js
  packages/gatsby-theme-carbon/src/components/Code/_code.scss
  packages/gatsby-theme-carbon/src/components/Code/prismTheme.js
  packages/gatsby-theme-carbon/src/components/MDXProvider/defaultComponents.js
  packages/gatsby-theme-carbon/src/styles/index.scss
  packages/gatsby-theme-carbon/src/styles/internal/_global.scss
  yarn.lock
Labels: status: ready for review :eyes:, status: visual review :eyes:

#274 fix: update page tabs spacing at mobile
  packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.module.scss
Labels: status: ready for review :eyes:

#280 fix: remove janky :active class from tabs component
  packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss
Labels: status: one more review :eyes:

#273 fix: update icon sizing for resource cards
  .gitignore
  packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card.scss
Labels: status: ready for review :eyes:

#289 Next prev accordion
  packages/gatsby-theme-carbon/src/components/Accordion/Accordion.js
  packages/gatsby-theme-carbon/src/components/Code/Code.module.scss
  packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.module.scss
Labels: status: visual review :eyes:
