Repository carbon-design-system/gatsby-theme-carbon, pull requests merged in 2019-08, with the labels that each got.

#296 fix: homepage style bugs
  packages/gatsby-theme-carbon/src/components/Container/Container.js
  packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss
  packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss
  packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card-group.scss
Labels: status: ready for review :eyes:

#295 fix: extra space below images in dodont
  packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss
Labels: status: ready for review :eyes:

#292 feat: pass MDX frontmatter title into page `<title>`
  packages/example/src/pages/components/markdown.mdx
  packages/example/src/pages/guides/configuration.mdx
  packages/example/src/pages/index.mdx
  packages/gatsby-theme-carbon/gatsby-node.js
  packages/gatsby-theme-carbon/src/components/Layout.js
  packages/gatsby-theme-carbon/src/components/Meta.js
  packages/gatsby-theme-carbon/src/templates/Default.js
  packages/gatsby-theme-carbon/src/templates/Homepage.js
  yarn.lock
Labels: status: ready for review :eyes:

#303 fix: update switcher link for Enterprise Design Thinking
  packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js
Labels: status: ready for review :eyes:

#313 fix: update type token for blockquote to be responsive
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
Labels: status: one more review :eyes:

#321 fix(blockquote): list text color
  packages/example/src/pages/components/markdown.mdx
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
Labels: status: one more review :eyes:

#319 fix(DoDontExample): changed targeted class so video button is not off center
  packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss
Labels: status: one more review :eyes:

#322 fix(autolinkheader): no hover icon on small screens
  packages/gatsby-theme-carbon/src/components/AutolinkHeader/AutolinkHeader.module.scss
Labels: status: one more review :eyes:

#283 feat: add support for dark mode pages
  packages/example/src/pages/components/Accordion.mdx
  packages/example/src/pages/gallery/index.mdx
  packages/example/src/pages/guides/configuration.mdx
  packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLinks.module.scss
  packages/gatsby-theme-carbon/src/components/Aside/Aside.module.scss
  packages/gatsby-theme-carbon/src/components/Container/Container.js
  packages/gatsby-theme-carbon/src/components/EditLink/EditLink.module.scss
  packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss
  packages/gatsby-theme-carbon/src/components/ImageCard/image-card.scss
  packages/gatsby-theme-carbon/src/components/Layout.js
  packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.js
  packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.module.scss
  packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItem.js
  packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.module.scss
  packages/gatsby-theme-carbon/src/components/PageDescription/PageDescription.module.scss
  packages/gatsby-theme-carbon/src/components/PageTable/page-table.scss
  packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
  packages/gatsby-theme-carbon/src/templates/Default.js
Labels: status: one more review :eyes:

#325 fix: remove extra spacing in aside component
  packages/example/src/pages/components/Aside.mdx
  packages/gatsby-theme-carbon/src/components/Aside/Aside.module.scss
Labels: status: ready for review :eyes:

#332 refactor: remove addons-website dependency
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.js
  packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.module.scss
  packages/gatsby-theme-carbon/src/components/BackToTopBtn/index.js
  packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
  packages/gatsby-theme-carbon/src/styles/internal/_global.scss
  packages/gatsby-theme-carbon/src/styles/internal/_page.scss
  packages/gatsby-theme-carbon/src/styles/internal/_website-side-nav.scss
  packages/gatsby-theme-carbon/src/templates/Default.js
  packages/gatsby-theme-carbon/src/templates/Homepage.js
  yarn.lock
Labels: status: one more review :eyes:

#335 fix: update callout header to expressive heading 03
  packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss
Labels: status: one more review :eyes:, status: ready for review :eyes:

#342 fix: update header hide only at mobile
  packages/gatsby-theme-carbon/src/components/Header/Header.js
  packages/gatsby-theme-carbon/src/templates/Default.js
  packages/gatsby-theme-carbon/src/util/hooks/useScrollDirection.js
  packages/gatsby-theme-carbon/src/util/hooks/useScrollPosition.js
Labels: status: visual review :eyes:

#339 feat: update switcher at lg+ sizes
  packages/gatsby-theme-carbon/src/components/Header/Header.js
  packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
  packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js
  packages/gatsby-theme-carbon/src/components/Switcher/Switcher.module.scss
Labels: status: visual review :eyes:

#348 fix: add right border back to nav on dark
  packages/gatsby-theme-carbon/src/styles/internal/_website-side-nav.scss
Labels: status: ready for review :eyes:

#351 fix: list spacing
  packages/example/src/pages/components/markdown.mdx
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
Labels: status: ready for review :eyes:, status: visual review :eyes:

#350 fix: spacing updates / fixes
  packages/example/src/pages/components/Aside.mdx
  packages/example/src/pages/demo/index.mdx
  packages/gatsby-theme-carbon/src/components/Aside/Aside.module.scss
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
Labels: status: ready for review :eyes:

#363 fix: callout font size
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss
  yarn.lock
Labels: status: ready for review :eyes:

#315 feat(ImageGallery): adds ImageGallery and ImageGalleryImage component for gallery view of photos
  packages/example/src/data/nav-items.yaml
  packages/example/src/pages/components/ImageGallery.mdx
  packages/example/src/pages/components/images/IBM_Cloud_Data_Center.jpg
  packages/example/src/pages/components/images/IBM_Cloud_Developers.jpg
  packages/example/src/pages/components/images/IBM_Cloud_Interconnect.jpg
  packages/example/src/pages/components/images/IBM_Cloud_Logo.png
  packages/example/src/pages/components/images/IBM_Cloud_Notebook.jpg
  packages/example/src/pages/components/images/IBM_Cloud_Pictograms.gif
  packages/example/src/pages/components/images/IBM_Cloud_Platform_Prototype.gif
  packages/example/src/pages/components/images/IBM_Cloud_Server.png
  packages/example/src/pages/components/images/IBM_Cloud_Think_Keynote.jpg
  packages/example/src/pages/components/images/IBM_Design_landing.jpg
  packages/example/static/images/npm.svg
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/ImageGallery/ImageGallery.js
  packages/gatsby-theme-carbon/src/components/ImageGallery/ImageGallery.module.scss
  packages/gatsby-theme-carbon/src/components/ImageGallery/ImageGalleryImage.js
  packages/gatsby-theme-carbon/src/components/ImageGallery/ImageGalleryImage.module.scss
  packages/gatsby-theme-carbon/src/components/ImageGallery/index.js
  packages/gatsby-theme-carbon/src/components/MDXProvider/defaultComponents.js
Labels: status: ready for review :eyes:, status: visual review :eyes:

#329 feat: IBM Plex Sans Variable
  packages/gatsby-theme-carbon/gatsby-config.js
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.module.scss
  packages/gatsby-theme-carbon/src/styles/fonts/IBMPlexSans-Italic-VF.woff2
  packages/gatsby-theme-carbon/src/styles/fonts/IBMPlexSans-SemiBold.woff
  packages/gatsby-theme-carbon/src/styles/fonts/IBMPlexSans-VF.woff2
  packages/gatsby-theme-carbon/src/styles/fonts/IBMPlexSans.woff
  packages/gatsby-theme-carbon/src/styles/internal/_global.scss
  packages/gatsby-theme-carbon/src/styles/internal/_plex.scss
  scripts/IBMPlexSans-Italic-VF.ttf
  scripts/IBMPlexSans-VF.ttf
  scripts/subset.sh
  yarn.lock
Labels: status: ready to merge :tada:

#368 fix: article card type style and caption spacing
  packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLinks.module.scss
  packages/gatsby-theme-carbon/src/components/ArticleCard/article-card.scss
  packages/gatsby-theme-carbon/src/components/Caption/caption.scss
Labels: status: one more review :eyes:

#385 fix: add path prefix to poster
  packages/gatsby-theme-carbon/src/components/Video/Video.js
Labels: status: one more review :eyes:

#390 fix: Add switcher drop shadow closes #388
  packages/gatsby-theme-carbon/src/components/Switcher/Switcher.module.scss
Labels: status: visual review :eyes:
