Repository carbon-design-system/gatsby-theme-carbon, pull requests merged in 2019-09, with the labels that each got.

#404 feat: add prepend option to titleType
  packages/example/src/pages/guides/configuration.mdx
  packages/gatsby-theme-carbon/src/components/Meta.js
Labels: status: ready for review :eyes:

#384 feat: 🔥 native global search (client side) 🔥
  packages/example/gatsby-config.js
  packages/example/src/gatsby-theme-carbon/components/Header.js
  packages/example/src/pages/components/Accordion.mdx
  packages/example/src/pages/components/AnchorLinks.mdx
  packages/example/src/pages/components/ArtDirection/index.mdx
  packages/example/src/pages/components/ArticleCard.mdx
  packages/example/src/pages/components/Aside.mdx
  packages/example/src/pages/components/Caption.mdx
  packages/example/src/pages/components/DoDontExample.mdx
  packages/example/src/pages/components/FeatureCard.mdx
  packages/example/src/pages/components/Grid.mdx
  packages/example/src/pages/components/ImageCard.mdx
  packages/example/src/pages/components/ImageComponent.mdx
  packages/example/src/pages/components/ImageGallery.mdx
  packages/example/src/pages/components/PageDescription.mdx
  packages/example/src/pages/components/ResourceCard.mdx
  packages/example/src/pages/components/Tabs.mdx
  packages/example/src/pages/components/Video.mdx
  packages/example/src/pages/components/code-blocks.mdx
  packages/example/src/pages/components/markdown.mdx
  packages/example/src/pages/contributions.mdx
  packages/example/src/pages/demo/index.mdx
  packages/example/src/pages/gallery/index.mdx
  packages/example/src/pages/getting-started/index.mdx
  packages/example/src/pages/guides/configuration.mdx
  packages/example/src/pages/guides/navigation/sidebar.mdx
  packages/example/src/pages/guides/navigation/tabs.mdx
  packages/example/src/pages/guides/shadowing.mdx
  packages/example/src/pages/guides/styling.mdx
  packages/example/src/pages/test/spacing-audit.mdx
  packages/gatsby-theme-carbon/config/lunr-options.js
  packages/gatsby-theme-carbon/gatsby-config.js
  packages/gatsby-theme-carbon/gatsby-node.js
  packages/gatsby-theme-carbon/package.json
  packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js
  packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.module.scss
  packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearchInput.js
  packages/gatsby-theme-carbon/src/components/GlobalSearch/Menu.js
  packages/gatsby-theme-carbon/src/components/GlobalSearch/global-search.scss
  packages/gatsby-theme-carbon/src/components/Header/Header.js
  packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
  packages/gatsby-theme-carbon/src/components/Switcher/Switcher.module.scss
  packages/gatsby-theme-carbon/src/styles/index.scss
  packages/gatsby-theme-carbon/src/util/context/NavContext.js
  packages/gatsby-theme-carbon/src/util/hooks/index.js
  packages/gatsby-theme-carbon/src/util/hooks/useSearch.js
  yarn.lock
Labels: status: ready for review :eyes:, status: visual review :eyes:

#402 fix: update list alignment styles
  packages/example/src/pages/components/markdown.mdx
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
Labels: status: ready to merge :tada:

#429 feat: add InlineNotification component
  packages/example/src/data/nav-items.yaml
  packages/example/src/pages/components/InlineNotification.mdx
  packages/gatsby-theme-carbon/src/components/InlineNotification/InlineNotification.js
  packages/gatsby-theme-carbon/src/components/InlineNotification/InlineNotification.module.scss
  packages/gatsby-theme-carbon/src/components/InlineNotification/index.js
  packages/gatsby-theme-carbon/src/components/MDXProvider/defaultComponents.js
Labels: status: one more review :eyes:

#399 fix(Code): align code blocks in lists; closes #398
  packages/example/src/pages/components/code-blocks.mdx
  packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
Labels: status: waiting for response :thought_balloon:
